ASSUME CS:CODE, DS:DATA, SS:STACK
DATA   SEGMENT
BUFF   DB 'hello,world!', '$'
DATA   ENDS
STACK  SEGMENT STACK
STACK  ENDS
CODE   SEGMENT
MAIN:  MOV AX, DATA
       MOV DS, AX
       LEA DX, BUFF
       MOV AH, 09H
       INT 21H
       MOV AH, 4CH
       INT 21H
CODE   ENDS
END    MAIN