ASSUME CS:CODE, DS:DATA, SS:STACK
DATA   SEGMENT
LIST   DW 12,7,19,8,24
COUNT  EQU ($-LIST)/2
DATA   ENDS
STACK  SEGMENT STACK
STACK  ENDS
CODE   SEGMENT
MAIN:  MOV AX, DATA
       MOV DS, AX
       MOV CX, COUNT-1
LP1:   MOV DX, CX
       MOV BX, 0H
LP2:   MOV AX, LIST[BX]
       CMP AX, LIST[BX+2]
       JBE AGAIN
       XCHG AX, LIST[BX+2]
       MOV LIST[BX], AX
AGAIN: ADD BX, 2H
       LOOP LP2
       MOV CX, DX
       LOOP LP1
       MOV AH, 4CH
       INT 21H
CODE   ENDS
END    MAIN